### PR TITLE
Discard scheduled snapshots that are no longer required

### PR DESCRIPTION
**Pull request by jonathanrohland**
We are using k8s-snapshots in multiple clusters where it is responsible for the snapshots of up-to 7 different volumes at a time. We also run a custom cronjob in the cluster that periodically mounts the latest snapshots to create tar-files for persistent backups.

With this setup we experienced the following problem: The persistent volumes created by our tar-uploader created a lot of volume and pvc-events which each led to a backup being scheduled. Since multiple of the cronjobs ran at once this meant that the same backup was being scheduled for each backup. The backuper-task then ran in circles creating and immediately expiring backups for the same volume.
Since each created backup again triggered another backup and on each loop of the backuper only one scheduled backup was pulled the queue was never emptied again and kept increasing.

Our solution to the problem is to check whether a backup is still required each time before actually calling `make_backup`. Unfortunately this requires another query to the snapshots-api, but I think this is tolerable compared to the api-call for performing the actual backup (and if one considers the extra work of performing the same backup twice due to duplicate scheduling one even performs less work).

This should allso fix https://github.com/miracle2k/k8s-snapshots/issues/28

Before I end: Thanks for providing this very useful tool on github! This saved us a lot of work end even though it took us some time to understand what actually happened inside the snapshotter, we found implementing the changes necessary to fix the issue for us very straightforward due to the nice structure in your repo 👍 

PS: I fixed some types and typos along the way, hope you don't mind.

### CODE REVIEW

**Comment by miracle2k** [comment]
I overlooked this pull request, sorry about that! Will try to have a closer look at it soon.

**Comment by timstoop** [comment]
Hi,

We tried this (as the current build of k8s-snapshots seems to fall over quite often), but this breaks with the following stacktrace:

```
2018-11-13T08:30:57.587818Z Unhandled exception in main task [k8s_snapshots.__main__] loop=<_UnixSelectorEventLoop running=False closed=False debug=False> main_task=<Task finished coro=<daemon() done, defined at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py:585> exception=TypeError("'coroutine' object is not iterable",)> message=Unhandled exception in main task severity=ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/__main__.py", line 58, in main
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 610, in daemon
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 574, in backuper
    if await is_snapshot_required(ctx, current_target_rule):
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 412, in is_snapshot_required
    return snapshots_for_rule_are_outdated(rule, all_snapshots)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 416, in snapshots_for_rule_are_outdated
    snapshot_times = get_snapshot_times_for_rule(existing_snapshots, rule)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 395, in get_snapshot_times_for_rule
    snapshots_for_rule = filter_snapshots_by_rule(snapshots, rule)
  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 406, in filter_snapshots_by_rule
    return filter(match_disk, snapshots)
TypeError: 'coroutine' object is not iterable
```

My experience with Python's asyncio is 0, but I tried to look into it anyway. To me, it seems like the `snapshot_results` variable defined in line 349 in snapshot.py is not actually `await`ing (or I misunderstand what `await` does, I expected it to simply wait until it gets all results back and only then continue with the rest of the code) but passing on the actual Task instead. There my understanding of the code stops.

Hope this helps.

**Comment by jonathanrohland** [comment]
@timstoop Thanks for the hint, there was indeed an await statement missing. I am not sure why this didn't crash on our machines yet. Do you mind checking again whether this is working correctly now?

**Comment by timstoop** [comment]
Just deployed the image with your fix! It took a bit last time before it started crashing, so I'll report back tomorrow.

**Comment by timstoop** [comment]
Works stable and seems to solve the problem indeed! Thank you!

**Comment by robinro** [comment]
@miracle2k Any news on getting this merged?

**Comment by rohlandj** [comment]
@miracle2k Did you have time to take a look at this in the meantime? Do you need anything from us in order to merge this?

**Comment by jonathanrohland** [comment]
@miracle2k Did you have a chance to  take a look at this in the meantime? We've been using the patched version in production for the last year and didn't notice any problems.

**Comment by miracle2k** [comment]
I was experimenting with refactoring the code that does the snapshotting, but I've dropped that attempt for now, so I'll merge this one instead. Sorry it took so long.

**Pull request merged**
